export const SET_MOVIES = "SET_MOVIES";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_LOADING = "SET_LOADING";
export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD";
export const SET_MOVIE_DETAILS = "SET_MOVIE_DETAILS"
